# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine: true

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: Install OpenJDK 11
          command: |
            wget https://download.java.net/java/GA/jdk11/13/GPL/openjdk-11.0.1_linux-x64_bin.tar.gz
            gunzip -c openjdk-11.0.1_linux-x64_bin.tar.gz | tar xopf -
            echo "export JAVA_HOME=`pwd`/jdk-11.0.1" >> $BASH_ENV
            echo "export PATH=`pwd`/jdk-11.0.1/bin:$PATH" >> $BASH_ENV
      
      - run:
          name: Install Bazel
          command: |
            sudo apt-get install pkg-config zip g++ zlib1g-dev unzip python
            wget https://github.com/bazelbuild/bazel/releases/download/0.25.0/bazel-0.25.0-installer-linux-x86_64.sh
            chmod +x bazel-0.25.0-installer-linux-x86_64.sh
            ./bazel-0.25.0-installer-linux-x86_64.sh --user
            echo "export PATH=$PATH:$HOME/bin" >> $BASH_ENV
      
      - run:
          name: Verify environment
          command: |
            java -version
            bazel version
        
      - run: mvn test


